name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v3.2.0-node20
      with:
        name: hello-artifact
        path: hello.txt
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download 
      uses: actions/download-artifact@v4.1.8
      with: 
        name: hello-artifact
        path: ./artifacts
    - name: read the file
      run: cat ./artifacts/hello.txt


